language: objective-c
osx_image: xcode8
sudo: false
notifications:
  email: false
before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail
  - xcodebuild -workspace "apple/diffreport.xcworkspace" -scheme "diffreportlib" -configuration "Debug" -destination "platform=macOS" -enableCodeCoverage "YES" test | xcpretty
after_success:
  - bash <(curl -s https://codecov.io/bash)
