language: objective-c
osx_image: xcode10
sudo: false
notifications:
  email: false
before_install:
  - gem install xcpretty sourcekitten --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail
  - cd apple/diffreport
  - swift test
after_success:
  - bash <(curl -s https://codecov.io/bash)
